import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';
import '../css/style.scss';

export const metadata = {
  title: 'Needl: Recruitment, done better!',
  description: 'Generated by create next app',
  metadataBase: new URL('https://needl.io'),
  alternates: {
    canonical: '/',
  },
  openGraph: {
    images: '/og-image.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
